FROM node:boron

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app/
RUN npm install

COPY . /usr/src/app

ENV DTTENANT [YOURTENANTID]
ENV DTAPITOKEN [YOURTOKEN]
ENV DTMANAGED [1IFMANAGED]
ENV DTHOST [YOURHOSTIFMANAGED]
ENV ITOPHOST [YOURITOPHOST]
ENV ITOPPORT [YOURITOPPORT]
ENV ITOPUSER [YOURITOPUSER]
ENV ITOPPASS [YOURITOPPASS]


CMD ["node", "app.js"]